name: advent
version: 0.1.0.0
synopsis: Solutions for the Advent of Code 2016
description: Please see README.md
license: BSD3
author: Patrick Herrmann
maintainer: patrickwherrmann@gmail.com
copyright: (c) 2016 Patrick Herrmann
category: Misc

github: patrickherrmann/advent2016

default-extensions:
  - NoImplicitPrelude
  - LambdaCase
  - GeneralizedNewtypeDeriving
  - ViewPatterns
  - BangPatterns
  - DeriveGeneric
  - OverloadedStrings
  - FlexibleContexts

ghc-options:
  -Wall
  -Wno-incomplete-patterns
  -Wno-unused-do-bind

dependencies:
  - base
  - bytestring
  - protolude
  - text

library:
    source-dirs: src
    dependencies:
      - array
      - base16-bytestring
      - containers
      - cryptohash
      - megaparsec
      - multimap
      - lens
      - split
      - vector

tests:
  advent-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - advent
      - hspec
